-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 09:27:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_authorized`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_authorized` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_authorized` (
  `usn` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `hashed_password` CHAR(128) NOT NULL,
  `pregnancy_month` TINYINT NOT NULL,
  `birth` VARCHAR(8) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `state` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `verfication_code_cpw` VARCHAR(64) NOT NULL,
  `is_sign_in` TINYINT(2) NOT NULL,
  PRIMARY KEY (`usn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`device` ;

CREATE TABLE IF NOT EXISTS `mydb`.`device` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `usn` INT NOT NULL,
  `device_name` VARCHAR(64) NOT NULL,
  `mac` CHAR(17) NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `usn_idx` (`usn` ASC) ,
  CONSTRAINT `usn_device`
    FOREIGN KEY (`usn`)
    REFERENCES `mydb`.`user_authorized` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`polar_sensor_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`polar_sensor_data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`polar_sensor_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usn` INT NOT NULL,
  `heart_rate` TINYINT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usn_idx` (`usn` ASC) ,
  CONSTRAINT `usn_polar`
    FOREIGN KEY (`usn`)
    REFERENCES `mydb`.`user_authorized` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airQuality_sensor_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`airQuality_sensor_data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`airQuality_sensor_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ssn` INT NOT NULL,
  `usn` INT NOT NULL,
  `PM10` FLOAT NOT NULL,
  `CO` FLOAT NOT NULL,
  `SO2` FLOAT NOT NULL,
  `O3` FLOAT NOT NULL,
  `NO2` FLOAT NOT NULL,
  `temperature` FLOAT NOT NULL,
  `PM2.5` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  INDEX `usn_idx` (`usn` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `usn_airQuality`
    FOREIGN KEY (`usn`)
    REFERENCES `mydb`.`user_authorized` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ssn`
    FOREIGN KEY (`ssn`)
    REFERENCES `mydb`.`device` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_temporary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_temporary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_temporary` (
  `email` VARCHAR(128) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `hashed_password` CHAR(128) NOT NULL,
  `pregnancy_month` TINYINT NOT NULL,
  `birth` VARCHAR(8) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `verification_code` VARCHAR(64) NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`display_realtime_airQuality_Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`display_realtime_airQuality_Data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`display_realtime_airQuality_Data` (
  `usn` INT NOT NULL,
  `ssn` INT NOT NULL,
  `PM10` FLOAT NOT NULL,
  `CO` FLOAT NOT NULL,
  `SO2` FLOAT NOT NULL,
  `O3` FLOAT NOT NULL,
  `NO2` FLOAT NOT NULL,
  `temperature` FLOAT NOT NULL,
  `PM2.5` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`usn`),
  INDEX `ssn_idx` (`ssn` ASC) ,
  CONSTRAINT `ssn_realtime_airQuality`
    FOREIGN KEY (`ssn`)
    REFERENCES `mydb`.`device` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`display_realtime_polar_Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`display_realtime_polar_Data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`display_realtime_polar_Data` (
  `usn` INT NOT NULL,
  `heart_rate` TINYINT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `datetime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`usn`),
  CONSTRAINT `usn_realtime_polar`
    FOREIGN KEY (`usn`)
    REFERENCES `mydb`.`user_authorized` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_authorized`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hospital_authorized` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hospital_authorized` (
  `hospital_usn` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `hashed_password` CHAR(128) NOT NULL,
  `hospital_name` VARCHAR(64) NOT NULL,
  `tel` CHAR(13) NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  `zip` CHAR(5) NOT NULL,
  `state` VARCHAR(64) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `is_sign_in` TINYINT NOT NULL,
  PRIMARY KEY (`hospital_usn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_temporary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hospital_temporary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hospital_temporary` (
  `email` VARCHAR(128) NOT NULL,
  `hashed_password` CHAR(128) NOT NULL,
  `hospital_name` VARCHAR(64) NOT NULL,
  `tel` CHAR(13) NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  `zip` CHAR(5) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `verification_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
